name: Static website uploading & testing

on: 
  push:
    branches: ["main"]

jobs:
  build: 
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  docker-login:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

  testing:
    needs: docker-login
    runs-on: ubuntu-latest
    steps:
    - run: ls

  docker-push:
    needs: docker-login
    runs-on: ubutu-latest
    steps:
    - uses: docker/build-push-action@v4
      with:
        push: true
        tags: asifrehmani/carville:latest
