name: Static website uploading & testing

on: 
  push:
    branches: ["main"]

jobs:
  build: 
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  dockerlogin:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        push: true
        tags: asifrehmani/carville:$GITHUB_RUN_ATTEMPT
